project:
  type: book
  output-dir: _book

book:
  title: "Basis functions of Finite Element Methods"
  author: "Vikas Sharma"
  date: "1/27/2025"
  reader-mode: true
  search: true
  repo-url: https://github.com/poromechanics/basis-fem/
  site-url: https://poromechanics.github.io/basis-fem
  repo-actions: [edit, issue]
  downloads: [pdf,epub]
  sharing: [twitter, linkedin]
  favicon: ./figures/favicon.png
  cover-image: ./figures/cover.svg
  cover-image-alt: Basis functions of FEM
  twitter-card: true
  page-navigation: true
  page-footer: 
    left: "Copyright 2025, Vikas Sharma" 
    right: 
      - icon: github
        href: https://github.com/vickysharma0812
      - icon: twitter
        href: https://twitter.com/vickysharma0812
      - icon: linkedin
        href: https://linkedin.com/in/vickysharma0812
  sidebar:
      style: docked
      background: light
  chapters:
    - index.md
    - intro.md
    - summary.md
    - references.md

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  # pdf:
  #   documentclass: scrreprt



